# Orion Configuration with TLV Listener Filter Enabled

runtime:
  num_cpus: 1
  num_runtimes: 1

logging:
  log_level: "debug"

envoy_bootstrap:
  admin:
    address:
      socket_address:
        address: "127.0.0.1"
        port_value: 9901

  static_resources:
    listeners:
    - name: "tlv_demo_listener"
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: 10000
      listener_filters:
        - name: "envoy.listener.kmesh_tlv"
          typed_config:
            "@type": "type.googleapis.com/udpa.type.v1.TypedStruct"
            "type_url": "type.googleapis.com/envoy.extensions.filters.listener.kmesh_tlv.v3.KmeshTlv"
            "value": {}
      filter_chains:
      - name: "default_filter_chain"
        filters:
        - name: "envoy.filters.network.http_connection_manager"
          typedConfig:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            codec_type: AUTO
            stat_prefix: tlv_demo
            httpFilters:
            - name: "envoy.filters.http.router"
              typedConfig:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            routeConfig:
              name: "local_route"
              virtualHosts:
              - name: "demo"
                domains: ["*"]
                routes:
                - match:
                    prefix: "/"
                  direct_response:
                    status: 200
                    body:
                      inline_string: "TLV Filter Test - Success!"

    clusters:
    - name: "dummy_cluster"
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: "127.0.0.1"
                  port_value: 8080
