use bitflags::bitflags;
use http::HeaderName;

bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Category: u16 {
        const INIT_CONTEXT = 1;
        const FINISH_CONTEXT = 1 << 1;
        const UPSTREAM_CONTEXT = 1 << 2;
        const DOWNSTREAM_CONTEXT = 1 << 3;
        const DOWNSTREAM_REQUEST = 1 << 4;
        const DOWNSTREAM_RESPONSE = 1 << 5;
        const UPSTREAM_REQUEST = 1 << 6;
        const UPSTREAM_RESPONSE = 1 << 7;
        const ARGUMENT = 1 << 8;
    }
}

#[derive(Clone, PartialEq, Hash, Debug)]
pub enum Token {
    RequestDuration,
    RequestTxDuration,
    ResponseDuration,
    ResponseTxDuration,
    DownstreamHandshakeDuration,
    RoundtripDuration,
    BytesReceived,
    BytesRetransmitted,
    PacketsRetransmitted,
    UpstreamWireBytesReceived,
    UpstreamHeaderBytesReceived,
    DownstreamWireBytesReceived,
    DownstreamHeaderBytesReceived,
    Protocol,
    UpstreamProtocol,
    ResponseCode,
    ResponseCodeDetails,
    ConnectionTerminationDetails,
    BytesSent,
    UpstreamWireBytesSent,
    UpstreamHeaderBytesSent,
    DownstreamWireBytesSent,
    DownstreamHeaderBytesSent,
    Duration,
    CommonDuration,
    CustomFlags,
    ResponseFlags,
    ResponseFlagsLong,
    UpstreamHostName,
    UpstreamHostNameWithoutPort,
    UpstreamHost,
    UpstreamConnectionId,
    UpstreamCluster,
    UpstreamClusterRaw,
    UpstreamLocalAddress,
    UpstreamLocalAddressWithoutPort,
    UpstreamLocalPort,
    UpstreamRemoteAddress,
    UpstreamRemoteAddressWithoutPort,
    UpstreamRemotePort,
    UpstreamRequestAttemptCount,
    UpstreamTlsCipher,
    UpstreamTlsVersion,
    UpstreamTlsSessionId,
    UpstreamPeerIssuer,
    UpstreamPeerCert,
    UpstreamPeerSubject,
    DownstreamLocalAddress,
    DownstreamDirectLocalAddress,
    DownstreamLocalAddressWithoutPort,
    DownstreamDirectLocalAddressWithoutPort,
    DownstreamLocalPort,
    DownstreamDirectLocalPort,
    DownstreamRemoteAddress,
    DownstreamRemoteAddressWithoutPort,
    DownstreamRemotePort,
    DownstreamDirectRemoteAddress,
    DownstreamDirectRemoteAddressWithoutPort,
    DownstreamDirectRemotePort,
    ConnectionId,
    RequestedServerName,
    RouteName,
    UpstreamPeerUriSan,
    UpstreamPeerDnsSan,
    UpstreamPeerIpSan,
    UpstreamLocalUriSan,
    UpstreamLocalDnsSan,
    UpstreamLocalIpSan,
    DownstreamPeerUriSan,
    DownstreamPeerDnsSan,
    DownstreamPeerIpSan,
    DownstreamPeerEmailSan,
    DownstreamPeerOthernameSan,
    DownstreamLocalUriSan,
    DownstreamLocalDnsSan,
    DownstreamLocalIpSan,
    DownstreamLocalEmailSan,
    DownstreamLocalOthernameSan,
    DownstreamPeerSubject,
    DownstreamLocalSubject,
    DownstreamTlsSessionId,
    DownstreamTlsCipher,
    DownstreamTlsVersion,
    DownstreamPeerFingerprint256,
    DownstreamPeerFingerprint1,
    DownstreamPeerSerial,
    DownstreamPeerChainFingerprints256,
    DownstreamPeerChainFingerprints1,
    DownstreamPeerChainSerials,
    DownstreamPeerIssuer,
    DownstreamPeerCert,
    DownstreamTransportFailureReason,
    UpstreamTransportFailureReason,
    Hostname,
    FilterChainName,
    VirtualClusterName,
    TlsJa3Fingerprint,
    UniqueId,
    StreamId,
    StartTime,
    StartTimeLocal,
    EmitTime,
    EmitTimeLocal,
    DynamicMetadata,
    ClusterMetadata,
    UpstreamMetadata,
    FilterState,
    UpstreamFilterState,
    DownstreamPeerCertVStart,
    DownstreamPeerCertVEnd,
    UpstreamPeerCertVStart,
    UpstreamPeerCertVEnd,
    Environment,
    UpstreamConnectionPoolReadyDuration,
    Request, // placeholder
    RequestScheme,
    RequestMethod,
    RequestPath,
    RequestOriginalPathOrPath,
    RequestAuthority,
    RequestStandard(HeaderName),
    Response, // placeholder
    ResponseStandard(HeaderName),
}
